services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      BACKEND_API_URL: ${BACKEND_API_URL:-http://localhost:3000/v1}
    ports:
      - '3001:3000'
